---
title: "README"
author: "Linda Kukolich"
date: "January 22, 2015"
output: html_document
---

## run_analysis.R

This R script was written for the class project assigned as part of
**Getting and Cleaning Data**, a Coursera course taught by Jeff Leek, PhD,
Roger D. Peng, PhD, and Brian Caffo, PhD. The text of the assignment is
included below. In brief, this script downloads a dataset generated by test
subjects wearing a cellphone with an embedded accelerometer and gyroscope. The
original dataset contains multiple series of values derived from the cellphone
sensors. Each one of these series of values is averaged to give values in a new
dataset.

### Usage

Call **run_analysis()** to create and write the required data.frame

### Functions

- **downloadData()**
    Download and unzip the original data. This creates a directory
    containing documentation of the data set and subdiretories with many
    data files.
- **buildHarData()**
    read several of the data files downloaded by downloadData(). Use their
    contents to build a single data frame containing subject labels,
    activity labels, and selected data variables. Specifically:
    
    - Subject labels
        - "./data/UCI HAR Dataset/train/subject_train.txt"
        - "./data/UCI HAR Dataset/test/subject_test.txt"
    - Names of activities
        - "./data/UCI HAR Dataset/activity_labels.txt"
    - Activity labels
        - "./data/UCI HAR Dataset/train/y_train.txt"
        - "./data/UCI HAR Dataset/test/y_test.txt"
    - Names of all data variables
        - "./data/UCI HAR Dataset/features.txt"
    - Data variables
        - "./data/UCI HAR Dataset/train/X_train.txt"
        - "./data/UCI HAR Dataset/test/X_test.txt"
    
    The data variables selected have names that contain "mean()" or "std()",
    which gives a total of 66 selected data variables from the original 561.
- **averageData(DATAFRAME)**
    Take in a data.frame like the one built in buildHarData. Select rows,
    grouping them by subject and activity. Average the data variables in each
    group to give a total of n-subjects * n-activities rows. Also, alter the
    names of the data columns, adding avg_ to the beginning of each column name
    and removing ()
- **run_analysis()**
    Call the other functions in this file to create the data.frame requested
    in the assignment. Also, write the final data.frame to a text file.
- **test_averageData()**
    This test verifies the averageData function. Create a data.frame similar to
    the one created in buildHarData() and send it through averageData(). Prepare
    a matching data.frame with results that should match.

## Original Assignment

The purpose of this project is to demonstrate your ability to collect, work
with, and clean a data set. The goal is to prepare tidy data that can be used
for later analysis. You will be graded by your peers on a series of yes/no
questions related to the project. You will be required to submit: 1) a tidy data
set as described below, 2) a link to a Github repository with your script for
performing the analysis, and 3) a code book that describes the variables, the
data, and any transformations or work that you performed to clean up the data
called CodeBook.md. You should also include a README.md in the repo with your
scripts. This repo explains how all of the scripts work and how they are
connected.  

One of the most exciting areas in all of data science right now is wearable
computing - see for example this article . Companies like Fitbit, Nike, and
Jawbone Up are racing to develop the most advanced algorithms to attract new
users. The data linked to from the course website represent data collected from
the accelerometers from the Samsung Galaxy S smartphone. A full description is
available at the site where the data was obtained: 

[http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones]

Here are the data for the project: 

[https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip]

You should create one R script called run_analysis.R that does the following. 

- Merges the training and the test sets to create one data set.
- Extracts only the measurements on the mean and standard deviation for each
measurement. 
- Uses descriptive activity names to name the activities in the data set
- Appropriately labels the data set with descriptive variable names. 
- From the data set in step 4, creates a second, independent tidy data set with
the average of each variable for each activity and each subject.
